import {GridColDef} from "@mui/x-data-grid";

export const COLUMNS: GridColDef[] = [
    {
        field: "id",
        headerName: "מזהה",
        flex: 1,
        headerAlign: "center",
        align: "center",
        minWidth: 150,
    },
    {
        field: "name",
        headerName: "שם",
        flex: 1,
        headerAlign: "center",
        align: "center",
        minWidth: 150,
    },
    {
        field: "fileName",
        headerName: "שם קובץ",
        flex: 1,
        headerAlign: "center",
        align: "center",
        minWidth: 150,
    },
    {
        field: "format",
        headerName: "פורמט",
        flex: 1,
        headerAlign: "center",
        align: "center",
        minWidth: 150,
    },
    {
        field: "projectCode",
        headerName: "קוד פרויקט",
        flex: 1,
        headerAlign: "center",
        align: "center",
        minWidth: 150,
    },
    {
        field: "updateDate",
        headerName: "תאריך עדכון",
        flex: 1,
        headerAlign: "center",
        align: "center",
        minWidth: 150,
    },
    {
        field: "createDate",
        headerName: "תאריך יצירה",
        flex: 1,
        headerAlign: "center",
        align: "center",
        minWidth: 150,
    },
    {
        field: "revision",
        headerName: "גרסה",
        flex: 1,
        headerAlign: "center",
        align: "center",
        minWidth: 150,
    },
    {
        field: "isFinal",
        headerName: "סופי",
        flex: 1,
        headerAlign: "center",
        align: "center",
        type: "boolean",
        minWidth: 150,
    },
    {
        field: "revisionGroup",
        headerName: "קבוצת גרסאות",
        flex: 1,
        headerAlign: "center",
        align: "center",
        minWidth: 150,
    },
];